Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-062df10d14676e201
      InstanceType: t2.micro
      KeyName: KeyPair1_Mumbai
      SecurityGroups:
        - !Ref SecurityGroup1
      Tags: 
        - Key: Createdby
          Value: mohit
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt install apache2 -y
          echo "Hello" > /var/www/html/index.html
          
  SecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: sg for apache web server
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
